name: Example

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CPM_SOURCE_CACHE: ${{ github.workspace }}/cpm_modules

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: "**/cpm_modules"
          key: ${{ github.workflow }}-cpm-modules-${{ hashFiles('**/CMakeLists.txt', '**/*.cmake') }}

      - name: configure
        run: cmake -Sexamples/infinite_horizon_lqr -Bbuild/infinite_horizon_lqr -DCMAKE_BUILD_TYPE=Debug

      - name: build
        run: cmake --build build/infinite_horizon_lqr -j4

      - name: run
        run: ./build/infinite_horizon_lqr/main
